{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres          # este nome é o PROD_DB_HOST do app!
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: bunzina
spec:
  clusterIP: None         # headless: necessário para StatefulSet
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
{{- end }}