apiVersion: v1
kind: Secret
metadata:
  name: bunzina-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bunzina.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}