namespace: bunzina

image:
  repository: 955971900480.dkr.ecr.us-east-1.amazonaws.com/bunzina
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

config:
  APP_ENV: "prod"
  PROD_DB_HOST: "postgres"
  PROD_DB_PORT: "5432"
  PROD_DB_NAME: "bunzina"
  EMAIL_SMTP_HOST: "mailcatcher"
  EMAIL_SMTP_PORT: "1025"
  EMAIL: "no-reply@bunzina.local"
  JWT_EXPIRES_IN: "1d"

secret:
  PROD_DB_USER: "bun"
  PROD_DB_PASSWORD: "change-me"
  JWT_SECRET: "change-me-with-a-long-random-string"
  EMAIL_SMTP_USER: ""
  EMAIL_SMTP_PASSWORD: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

postgres:
  enabled: true
  image: postgres:15
  storage: 10Gi
  storageClassName: gp3
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  user: "bun"
  password: "change-me"
  db: "bunzina"
